version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  install-jdk:
    docker:
      - image: circleci/android:api-30
    steps:
      - checkout
      - run:
            name: Add Google Cloud SDK public key
            command: |
              curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
              echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk-buster main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
              sudo apt-get update
      - run:
          name: Install OpenJDK 17
          command: |
            sudo apt-get update && sudo apt-get install openjdk-17-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
            echo 'export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64/' >> ~/.circlerc

  unit-test:
    docker:
      - image: circleci/android:api-30
    steps:
      - run:
          name: Make gradlew executable
          command: chmod +x gradlew
      - run:
          name: Run Unit Tests
          command: ./gradlew testDebug

  android-test:
    docker:
      - image: circleci/android:api-30
    steps:
      - run:
          name: Make gradlew executable
          command: chmod +x gradlew
      - run:
          name: Run Instrumented Tests
          command: ./gradlew connectedAndroidTest

  release-build:
    docker:
      - image: circleci/android:api-30
    steps:
      - run:
          name: Make gradlew executable
          command: chmod +x gradlew
      - run:
          name: Assemble release build
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/release

workflows:
  test-and-build:
    jobs:
      - install-jdk
      - unit-test:
          requires:
            - install-jdk
      - android-test:
          requires:
            - install-jdk
      - release-build:
          requires:
            - unit-test
            - android-test
          filters:
            branches:
              only: main
