version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  install-jdk:
    docker:
      - image: circleci/android:api-30
    steps:
      - checkout
      - run:
          name: Install OpenJDK 17
          command: |
            sudo apt-get update && sudo apt-get install openjdk-17-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
            java -version

  unit-test:
    docker:
      - image: circleci/android:api-30
    steps:
      - run:
          name: Make gradlew executable
          command: chmod +x gradlew
      - run:
          name: Run Unit Tests
          command: ./gradlew testDebug

  android-test:
    docker:
      - image: circleci/android:api-30
    steps:
      - run:
          name: Make gradlew executable
          command: chmod +x gradlew
      - run:
          name: Run Instrumented Tests
          command: ./gradlew connectedAndroidTest

  release-build:
    docker:
      - image: circleci/android:api-30
    steps:
      - run:
          name: Make gradlew executable
          command: chmod +x gradlew
      - run:
          name: Assemble release build
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/release

workflows:
  test-and-build:
    jobs:
      - install-jdk
      - unit-test:
          requires:
            - install-jdk
      - android-test:
          requires:
            - install-jdk
      - release-build:
          requires:
            - unit-test
            - android-test
          filters:
            branches:
              only: main
